In [11]:
import numpy as np
import matplotlib.pyplot as plt


In [22]:
num_agents = 3
C = 0

X = np.zeros(num_agents)  # opinions matrix
STD = abs(np.random.normal(0, 0.2, size=num_agents))
A = np.identity(num_agents)
RT = np.zeros(num_agents)

print(STD)


[0.05741844 0.00509586 0.35915731]


In [ ]:
def get_X(X):
    for i in range(X.shape[0]):
        X[i] = np.random.normal(C, STD[i])
    return X

while True:
    X = get_X(X)
    print("X Before", X)
    X = np.matmul(A, X)
    print("X After", X)
    RT += 1 / (X - C)**2 / num_agents
    A[:] = RT / np.sum(RT)
    print("RT", RT)
    print("A", np.around(A, 2))

    if input():
        break

X Before [ 0.07481811  0.00516261 -0.22455203]
X After [ 0.07481811  0.00516261 -0.22455203]
RT [5.95477454e+01 1.25066352e+04 6.61065925e+00]
A [[0.   0.99 0.  ]
 [0.   0.99 0.  ]
 [0.   0.99 0.  ]]

X Before [8.63836812e-02 5.12479090e-05 5.87222330e-01]
X After [0.00076887 0.00076887 0.00076887]
RT [563924.54232555 576371.62974331 563871.60523936]
A [[0.33 0.34 0.33]
 [0.33 0.34 0.33]
 [0.33 0.34 0.33]]

X Before [ 0.090466   -0.00282354  0.51559579]
X After [0.19958036 0.19958036 0.19958036]
RT [563932.91073957 576379.99815733 563879.97365338]
A [[0.33 0.34 0.33]
 [0.33 0.34 0.33]
 [0.33 0.34 0.33]]


In [ ]:
a = np.array([ 502140.90216018, 1761549.84692459,  502183.39797852])
a/np.sum(a
        
        )

In [9]:
np.around(A, 2)

array([[0.33, 0.33, 0.33],
       [0.33, 0.33, 0.33],
       [0.33, 0.33, 0.33]])